


export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description:
            "Get interview questions and model answers basedon your role, experience and specific focus areas - no"
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description:
            "Expand answer only when you're ready. Dive deeper into any concept instantly with AI-powered deatiled"
    },
    {
        id: "03",
        title: "Capture Your Insights",
        description:
            "Add personal notes to any question and pin important ones to  the top - making your learning more organized"
    },
    {
        id: "04",
        title: 'Understand the "Why" Behind Answers',
        description:
            "Beyond just answers - unlock detailed concepts explanations generated by AI, helping you truely master each"
    },
    {
        id: "05",
        title: "Save, Organize and Revisit",
        description:
            "Easily save your interview sets, organize them neatly in your dashboard and pick up your preparation right"
    },
];